run10

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -4,7 +4,6 @@ env:
 steps:
   - label: ":docker: Build with Golang 1.18.0"
     command: |
-      go version
       go build -o output_binary /workdir/hello/hello.go
       chmod +x output_binary
       buildkite-agent artifact upload "output_binary"
@@ -25,17 +24,23 @@ steps:
         options:
           - label: "Okay"
             value: "okay"
+    command: |
+      buildkite-agent meta-data set release-name "${release-name}"
 
   - label: ":rocket: Deploy"
     command: |
       export USER_NAME=$(buildkite-agent meta-data get release-name)
+
+      if [ -z "$USER_NAME" ]; then
+        echo "Error: release-name metadata is empty!"
+        exit 1
+      fi
+     
       echo "Deploying for user: $USER_NAME"
-      buildkite-agent meta-data set release-name "$USER_NAME"
       buildkite-agent artifact download "output_binary" .
       chmod +x output_binary
       ./output_binary "$USER_NAME"
     plugins:
       - docker#v3.9.0:
           image: golang:${GO_VERSION}
-
 
